name: emirates_id_scanner
description: A package for swift and accurate scanning and data extraction from Emirates ID cards.
version: 0.0.5
homepage: https://github.com/OsamaAlhalabi/eid_scanner

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  google_mlkit_text_recognition: ^0.6.0
  intl: ^0.19.0
  path_provider: ^2.1.1
  camera: ^0.9.4
  camera_web: ^0.2.1+1
  image: ^4.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
